Remove rotten grey rules
rbkmoney/fraudbusters-management pull request #85
Opened 2021-06-01 08:34 UTC by ggmaleva

2021-06-03 07:27 UTC, strug requested changes

2021-06-03 07:27 UTC, strug commented on src/main/resources/db/migration/V1__init.sql
> +    CONSTRAINT wb_list_records_pkey PRIMARY KEY (id)
так нельзя надо вернуть старый файл и сделать alter для столбца в новом файле, flyway упадет при старте

2021-06-03 07:27 UTC, strug commented on src/test/java/com/rbkmoney/fraudbusters/management/dao/AbstractPostgresIntegrationTest.java
> -            flyway.migrate();
так точно все работает в тестах, я кажется делал не случайно были какие то траблы с миграцией)

2021-06-03 07:41 UTC, ggmaleva commented on src/main/resources/db/migration/V1__init.sql
> +    CONSTRAINT wb_list_records_pkey PRIMARY KEY (id)
да, тут тупанул, поправлю

2021-06-03 07:50 UTC, ggmaleva commented on src/test/java/com/rbkmoney/fraudbusters/management/dao/AbstractPostgresIntegrationTest.java
> -            flyway.migrate();
тесты поднялись :) а вообще @JooqTest под капотом несет FlywayAutoConfiguration

2021-06-03 09:16 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/service/GreyRottenRuleCleanerService.java
> +                    ""); // TODO инициатор нужен?
да нужен, должен быть fraudbusters

2021-06-03 09:16 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/service/GreyRottenRuleCleanerService.java
> +        wbListDao.removeRottenRecords(thresholdRotDate); // TODO а нужно ли оно?
это не нужно, на уровне листнера должно отработать

2021-06-03 09:16 UTC, strug commented on src/main/resources/db/migration/V1__init.sql
> +    CONSTRAINT wb_list_records_pkey PRIMARY KEY (id)
вот тут не должно быть вообще изменений, flyway просто по чексумме отбивает

2021-06-03 10:51 UTC, ggmaleva commented on src/main/java/com/rbkmoney/fraudbusters/management/service/GreyRottenRuleCleanerService.java
> +                    ""); // TODO инициатор нужен?
а это норм, что при отправке в риак он не используется?

2021-06-03 12:03 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/service/GreyRottenRuleCleanerService.java
> +                    ""); // TODO инициатор нужен?
> а это норм, что при отправке в риак он не используется?

нет это бага кажется, надо поправить по идеи

2021-06-15 12:04 UTC, strug approved these changes

2021-06-15 12:49 UTC, merged