Emulate data sets
rbkmoney/fraudbusters-management pull request #93
Opened 2021-08-16 11:10 UTC by strug

2021-08-30 06:17 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/converter/payment/PaymentApiToPaymentConverter.java
> +                        : new ProviderInfo())
Может вынесем в отдельный методы все подобные создания объектов?
К тому же ниже ты уже выносил `createError()`, `createClientInfo()`

2021-08-30 06:58 UTC, mr-impossibru requested changes

2021-08-30 06:58 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/converter/payment/TestPaymentModelToPaymentApiConverter.java
> +                        : null)
Похожий кусок кода выносил в отдельный метод в `PaymentApiToPaymentConverter`

2021-08-30 06:58 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/dao/payment/dataset/TestDataSetCheckingResultDao.java
> +public interface TestDataSetCheckingResultDao {
Очень не нравится `Test*` в начале названия, сразу ощущение каких-то тестовых фабрик, слоев и т.п.
Предлагаю перефразировать и заменить на `Validation`/`Verification`/`Examination`/`Sampling`/`Probe`/`Inspection`/`Assesment`/`Evaluation`/`Trial`, например, `DataSetAssesmentResultDao` или `DataSetInspectionResultDao` соответственно переименовать все схожие классы.

2021-08-30 06:58 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/dao/payment/dataset/TestDataSetDao.java
> +public interface TestDataSetDao {
переименоват, см коммент к `TestDataSetCheckingResultDao`

2021-08-30 06:58 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/dao/payment/dataset/TestDataSetDaoImpl.java
> +        dataSetModel.setLastModificationTime(null);
Это нужно принудительно занулять или перестраховываешься?

2021-08-30 06:58 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/dao/payment/dataset/TestPaymentDao.java
> +public interface TestPaymentDao {
переименовать, см коммент к `TestDataSetCheckingResultDao`

2021-08-30 14:56 UTC, strug commented on src/test/java/com/rbkmoney/fraudbusters/management/converter/payment/TestCheckedDataSetModelToCheckedDataSetApiConverterTest.java
> +@RunWith(SpringRunner.class)
> надо переезжать на junit5

заведем отдельную таску на это

2021-08-30 15:04 UTC, strug commented on pom.xml
> -        <version>1.2.9</version>
> мб бампанем до 15?

все сделаем в разрезе одной задачи рефактора

2021-08-30 15:12 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/payment/PaymentDataSetsResource.java
> +        log.info("getCheckedDataSet succeeded checkedDataSet: {}", dataSet);
> здесь и далее не очень нравится текст лога, мб
> log.info("Success get checkedDataSet : {}", dataSet)
> ну и в других методах аналогично

 ну тут я скорее за однообразный формат (привык к такому) - не вижу смысла закладывать карасату в такое. из преимуществ по моему можно найти по имени метода (по твоему в эластике ничего не найдется)

2021-08-30 15:27 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/exception/UnknownPaymentException.java
> +    public UnknownPaymentException() {
> вот это по-хорошему удалить надо, чтобы нечаянно анонимку не пробросить

тут не понял, что имеешь в виду? Она сама по себе несет достаточно информации

2021-08-30 15:28 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/payment/PaymentDataSetsResource.java
> +                                                           @Valid String dataSetName) {
> инсульт жеппы от такой идентации)))

тож не понял, так по свагу генерится, кажется нельзя сделать нормально) поэтому так если ты про параметры

2021-08-30 15:33 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/dao/payment/dataset/TestDataSetDaoImpl.java
> +        dataSetModel.setLastModificationTime(null);
> Это нужно принудительно занулять или перестраховываешься?

ну просто зачистка чтоб точно актуальная дата была при создании/обновлении

2021-08-31 08:28 UTC, D-Baykov commented on src/main/java/com/rbkmoney/fraudbusters/management/exception/UnknownPaymentException.java
> +    public UnknownPaymentException() {
Считаю, что в exception все-таки должен быть какой-то описывающий текст помимо инфы, которую ты выводишь из названия исключения, а пустой конструктор тебе позволяет такие исклчения бросать

2021-08-31 09:46 UTC, mr-impossibru approved these changes

2021-08-31 09:50 UTC, ggmaleva commented on src/main/resources/db/migration/V14__create_data_set.sql
> +CREATE TABLE af.test_data_set
а чего здесь test не заменил?

2021-08-31 09:50 UTC, ggmaleva commented on src/main/resources/db/migration/V14__create_data_set.sql
> +CREATE TABLE af.test_payment
и здесь тоже?

2021-08-31 09:50 UTC, ggmaleva commented on src/main/resources/db/migration/V15__create_checking_data_set_results.sql
> +CREATE TABLE af.test_data_set_checking_result
и тут тоже

2021-08-31 09:50 UTC, ggmaleva commented on src/main/resources/db/migration/V15__create_checking_data_set_results.sql
> +CREATE TABLE af.test_payment_checking_result
и тут test бы убрать

2021-08-31 10:49 UTC, strug commented on src/main/resources/db/migration/V14__create_data_set.sql
> +CREATE TABLE af.test_data_set
> а чего здесь test не заменил?

ну в базе мне норм так то) тут никому не мешает и понятно к чему это относится

2021-08-31 10:53 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/exception/UnknownPaymentException.java
> +    public UnknownPaymentException() {
> Считаю, что в exception все-таки должен быть какой-то описывающий текст помимо инфы, которую ты выводишь из названия исключения, а пустой конструктор тебе позволяет такие исклчения бросать

Можем обсудить, мне кажется странно писать примерно тоже самое в описании. Основной смысл, что отпачковываюсь от рантайма, чтобы если что отловить конкретную, ну и по названию тоже все сразу ясно, но если будет что-то подкапотное то уже добавится сообщение (ИМХО)

2021-08-31 11:20 UTC, ggmaleva commented on src/main/resources/db/migration/V14__create_data_set.sql
> +CREATE TABLE af.test_data_set
> > а чего здесь test не заменил?
> 
> ну в базе мне норм так то) тут никому не мешает и понятно к чему это относится

Не настаиваю. Думал, что мы везде убираем)

2021-08-31 11:26 UTC, ggmaleva approved these changes

2021-08-31 12:30 UTC, merged