Add new protocols for notifications
rbkmoney/fraudbusters-management pull request #96
Opened 2021-09-10 15:04 UTC by ggmaleva

2021-09-13 07:38 UTC, ggmaleva commented on src/main/java/com/rbkmoney/fraudbusters/management/service/ChannelServiceImpl.java
> +            return null;
может тут бросать исключение и пробрасывать 502 на фронт для информирования, что не достучался до нотификатора ?

2021-09-13 08:07 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/service/ChannelServiceImpl.java
> +            return null;
> может тут бросать исключение и пробрасывать 502 на фронт для информирования, что не достучался до нотификатора ?

 да давай

2021-09-13 08:08 UTC, strug commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/notificator/NotificationResource.java
> +        List<ChannelType> channelTypes = channelTypeListResponse.getChannelTypes().stream()
а почему ChannelType с вложенным type а не просто enum

2021-09-13 08:11 UTC, strug approved these changes

2021-09-13 13:08 UTC, strug submitted a review, later dismissed

2021-09-16 07:34 UTC, mr-impossibru requested changes

2021-09-16 07:34 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/config/NotificatorConfig.java
> +            throws IOException {
Форматирование съехало :)

2021-09-16 07:34 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/controller/ErrorController.java
> +    }
Может новый свитч забабахать? 
Красивее будет, да и потом новый код только одной строчкой добавить :)

2021-09-16 07:34 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/notificator/NotificationResource.java
> +        return ResponseEntity.ok(response);
В предыдущих методах ты конвертируешь внутри `ResponseEntity.ok()`, давай приведем к единому виду.

2021-09-16 07:34 UTC, mr-impossibru commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/notificator/NotificationResource.java
> +        return ResponseEntity.ok(response);
Нет логирования тут и в некоторых других методах по контроллеру.

2021-09-16 09:32 UTC, ggmaleva commented on src/main/java/com/rbkmoney/fraudbusters/management/controller/ErrorController.java
> +    }
Не воеришь, по началу так и начал делать. Потом до меня дошло, что 15 сюда еще не завезли. И с горя вернул на if. Поменяю на switch, чтобы потом на 15 переехать на новый

2021-09-16 09:34 UTC, ggmaleva commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/notificator/NotificationResource.java
> +        return ResponseEntity.ok(response);
вынес конвертер в ResponseEntity.ok()

2021-09-16 09:54 UTC, ggmaleva commented on src/main/java/com/rbkmoney/fraudbusters/management/resource/notificator/NotificationResource.java
> +        return ResponseEntity.ok(response);
добавил во все методы

2021-09-16 11:43 UTC, mr-impossibru approved these changes
Ждем 15ю джаву чтобы "make switch great again" :)

2021-09-16 12:21 UTC, merged